### ISSUE TITLE
Doing this project in Java.

### ISSUE THREAD

**Issue by Jack-O-Brian** [MuazAlhaidar/Winter-2021---Simple-Lander-Simulator---Console---Individual-Project-master#1]
![1568221844409](https://user-images.githubusercontent.com/40522299/108766353-0c8ffc00-7523-11eb-8f70-66daabd3039d.gif)
Have you have no self-respect? Do this in Kotlin at least

**Comment by MuazAlhaidar** [comment]
Solved:

The answer is no.
